Feat/#12 camera filter (1차구현)
Dolhareubang/hareubang-client pull request #20
Opened 2020-12-10 04:19 UTC by DonghyunKim98

2020-12-10 07:36 UTC, SaraHan774 reviewed
고친 내용들 다시 푸시할겡

2020-12-10 07:36 UTC, SaraHan774 commented on app/screens/FilterCamera/FilterCamera.tsx
>  function FilterCamera(): React.ReactNode {
React.ReactNode 타입으로 선언하면 
```
C:\Users\sarah\Desktop\RN\hareubang-client>yarn lint-fix
yarn run v1.22.5
$ tsc --noEmit && eslint "*/**/*.{js,ts,tsx}" --quiet --fix
app/App.tsx:21:6 - error TS2322: Type '() => ReactNode' is not assignable to type 'ComponentType<any>'.
  Type '() => ReactNode' is not assignable to type 'FunctionComponent<any>'.
    Type 'ReactNode' is not assignable to type 'ReactElement<any, any>'.      Type 'string' is not assignable to type 'ReactElement<any, any>'. 

21                              component={FilterCamera}
                                ~~~~~~~~~

  node_modules/@react-navigation/core/lib/typescript/src/types.d.ts:290:5
    290     component: React.ComponentType<any>;
            ~~~~~~~~~
    The expected type comes from property 'component' which is declared here on type '(IntrinsicAttributes & { name: "FilterCamera"; options?: StackNavigationOptions | ((props: { rout
here on type '(IntrinsicAttributes & { name: "FilterCamera"; options?: SOptions); listeners?: Partial<...> | ((props: { ...; }) => Partial<...>); initialParams?: object; } & { ...; })tackNavigationOptions | ((props: { route: Route<"FilterCamera", object>; navigation: any; }) => StackNavigationOptions); listeners?: Partial<...> | ((props: { ...; }) => Partial<...>); initialParams?: object; } & { ...; }) | (IntrinsicAttributes & ... 1 more ...'


Found 1 error.     
```
이런 린트 에러가 나와서 타입을 지워줬어용. 

App.tsx 파일에서 

```
				<Stack.Screen
					name="FilterCamera"
					component={FilterCamera}
					options={{title: 'Filter Camera'}}
				/>
```
이 부분의 component 프라퍼티가 받는 타입이 react node 가 아니다 .. 이런 에러인데 
찾아보니 타입스크립트의 한계인 것 같음.

2020-12-10 07:36 UTC, SaraHan774 commented on app/screens/FilterCamera/FilterCamera.tsx
>  	const SumbitBtnClickListener = () => {
Submit 인데 오타나서 고쳤음

2020-12-10 07:36 UTC, SaraHan774 commented on app/utils/imagePicker.ts
> +export const LaunchCamera = (option): Promise<string | any> => {
const FunctionName = (arg) : ArgType => { ... } 
이렇게 중괄호로 넣으면 안에다가 명시적으로 return( ... ); 을 넣어주는게 맞기는 한데, 
이런 경우는 보통 해당 블럭 안에서 return 말고도 다른 변수를 선언하거나 리턴 전에 별도의 로직 처리를 하는 경우라서 (블럭 스코프가 필요한 경우)

위에서는 중괄호 다음에 아무런 변수 선언이나 그런 것 없이 바로 return (new Promise ... ) 를 하기 때문에 
중괄호를 생략하고 바로 
 const FunctionName = (arg) : ArgType => ( 반환되는 것 ) 
이렇게 해주면 그냥 소괄호 안에 있는게 return 되는 효과가 있고, 이걸 활용하는게 좋다고 생각되어서 고쳤음 !

2020-12-10 07:57 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCamera.tsx
>  function FilterCamera(): React.ReactNode {
음... 나중에 refactor 이나 build에서 한번 더 작업해볼 부분인것같습니다.
일단은 이대로 진행할게요

2020-12-10 07:57 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCamera.tsx
>  	const SumbitBtnClickListener = () => {
고마워용

2020-12-10 07:58 UTC, DonghyunKim98 commented on app/utils/imagePicker.ts
> +export const LaunchCamera = (option): Promise<string | any> => {
처음에 Promise를 반환하기 전에 다른 로직 처리를 했어가지고 ㅋㅋㅋ
누나 말이 맞아요 감사합니다.

2020-12-11 01:50 UTC, YerinCho requested changes

2020-12-11 01:50 UTC, YerinCho commented on app/screens/FilterCamera/FilterCamera.tsx
> +			});
위에랑 중복되는부분 분리 가능할 듯 합니다

2020-12-11 01:50 UTC, YerinCho commented on app/utils/imagePicker.ts
> +		});
여기도 아래랑 코드중복 분리

2020-12-11 01:50 UTC, YerinCho commented on app/utils/imagePicker.ts
> +			if (res.error != null) {
null체크면 if(res.error) 로 가능하지 않나요?

2020-12-11 01:50 UTC, YerinCho commented on app/utils/imagePicker.ts
> +				resolve(res.uri);
if(!res.error) { resolve return;}
if(res.error.match){}

형식으로 하면 코드가 더 깔끔해지지 않을까요?

2020-12-11 01:55 UTC, DonghyunKim98 commented on app/utils/imagePicker.ts
> +		});
method를 어떤걸 쓸지 결정하는건데, 단순 if/else문 말고 다른 방안이 있나요?

2020-12-11 01:56 UTC, YerinCho commented on app/utils/imagePicker.ts
> +		});
똑같은 로직의 if/else문이 중복되어 있어서 이 부분을 함수로 빼면 중복을 줄일 수 있습니다~

2020-12-11 04:44 UTC, YerinCho requested changes

2020-12-11 04:44 UTC, YerinCho commented on app/screens/FilterCamera/FilterCamera.tsx
> +			</View>
여기 혹시 filterButtons 컴포넌트로 분리해보는 건 어때요 ㅎㅎ?
여기가 나중에 어떻게 추가될진 모르겠지만,,, 혹시 뭔가 더 추가될 예정이면,,, 미리 다른 컴포넌트로 분리하는것두,,,

2020-12-11 05:45 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCamera.tsx
> +			</View>
다음번 pr때 반영하겠음.
일단은 이번 pr까진 이렇게 갈게

2020-12-11 05:47 UTC, YerinCho commented on app/screens/FilterCamera/FilterCamera.tsx
> +			</View>
왜죠

2020-12-11 07:03 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCamera.tsx
> +			</View>
굳이 이번 PR 까진 반영할 이유가 없는 사안인것 같아서?

2020-12-11 13:28 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCamera.tsx
> +			</View>
반영했습니다

2020-12-12 04:52 UTC, YerinCho approved these changes

2020-12-12 07:19 UTC, SaraHan774 approved these changes
어푸르브

2020-12-12 07:19 UTC, merged