Feat/#12 camera filter 5
Dolhareubang/hareubang-client pull request #25
Opened 2020-12-28 05:43 UTC by DonghyunKim98

## 카메라 필터 5차 구현
*Hook을 이용하여, 필터 처리된 이미지 관련 value를 state로 처리 (서버에 데이터를 보내기 위함)
  * Image URI 값과 어떤 필터를 사용했는지 (틴트의 경우 amout값까지 조정)
  * Header Button은 Header Interaction을 사용
* Slider 배치 완료 (세로 배치는 아직 미지원)
------
* 지금 현재로는 필터를 위에 입히는 형식이 아니라서 슬라이더바로 조정했을때 새로 그려내지를 못합니다. 
코드를 어떤식으로 작성해야 스무스하게 렌더링할수 있을까요...?
    * 생각해본건, Tint Filter에 한정해서 hook을 연동하는 Component를 렌더링할 수 있도록 `FilterResultScreen.tsx` 에 관련 코드를 작성하는건데, 너무 지저분하고 가독성이 떨어질것 같습니다

2020-12-28 11:14 UTC, SaraHan774 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +	React.useLayoutEffect(() => {
submitBtnClickHandler 를 여기 안으로 옮기니까 린트 에러가 사라졌어용! 그리고 두번째인자로 [navigation, imgValue] 이렇게 바꾸어주니 빨간줄 사라짐

2020-12-28 11:14 UTC, SaraHan774 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				<Slider
```
JSX element class does not support attributes because it does not have a 'props' property
```
이렇게 빨간줄이 뜨는데 .. 흠

2020-12-29 02:16 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				<Slider
이 부분이 저도 처음에 이상했는데
제가 적용한 라이브러리에서, 'Slider'가 'React.Component' 를 상속받는 형식이더라고요.
그래서 JSX element class로 뜨는데 실제 동작하는데에는 아무런 문제가 없어요

2020-12-29 02:16 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +	React.useLayoutEffect(() => {
앗 감사합니당 반영해서 다시 푸쉬할게요

2020-12-31 01:10 UTC, YerinCho requested changes

2020-12-31 01:10 UTC, YerinCho commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				newImgValue.img = GrayscaledImage(imgUri, styles.img);
case에 해당하는 타입 스트링 상수화 가능할 것 같아요. "Tint" 의 경우 여러군데에서 사용하기 때문에 상수로 선언하고 사용하면 관리포인트도 줄어듭니다!

2020-12-31 01:15 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +			console.log(imgValue);
이 부분은 서버랑 통신하는 부분이라서 콘솔 로그로 내비둠

2020-12-31 01:16 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +		});
수정할게요!

2020-12-31 01:16 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +					maximumValue={2}
네엡!!

2020-12-31 01:17 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				newImgValue.img = GrayscaledImage(imgUri, styles.img);
그 부분에 대해서 생각을 해봤는데, 어떻게 처리해야할지 감이 안잡힘

2020-12-31 01:18 UTC, YerinCho commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				newImgValue.img = GrayscaledImage(imgUri, styles.img);
걍 constants.ts 에 다 때려박으면 됨 ㅋㅋ

2020-12-31 01:29 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				newImgValue.img = GrayscaledImage(imgUri, styles.img);
아 오키 ㅇㅋㅇㅋ

2020-12-31 02:03 UTC, DonghyunKim98 commented on app/screens/FilterCamera/FilterCameraResultScreen.tsx
> +				newImgValue.img = GrayscaledImage(imgUri, styles.img);
바뀐 부분 확인 부탁입니닷

2021-01-02 17:33 UTC, YerinCho approved these changes

2021-01-04 13:57 UTC, SaraHan774 approved these changes

2021-01-04 13:57 UTC, merged